### ISSUE TITLE
runtime error parsing results from dockerised gremlin-server 3.4.3

### ISSUE THREAD

**Issue by woodmawa** [microsoft/spring-data-gremlin#237]
**Your issue may already be reported! Please search before creating a new one.**

## Expected Behavior
built simple project to write graph to tinkerpop server in docker on local machine 

docker run --rm --name tinkerpop -p 8182:8182 -d tinkerpop/gremlin-server

## Current Behavior
* placeholder

## Possible Solution
* placeholder

## Steps to Reproduce (for bugs)
* download and run gremlin-sever v3.4.3 (latest for me)

* created simple spring-data-project 
github demo project is here 
[project](https://github.com/woodmawa/springdata-gremlin)

* build and run project

errors with this 
```
Caused by: java.lang.IllegalArgumentException: should contain a type property
	at org.springframework.util.Assert.isTrue(Assert.java:118) ~[spring-core-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultsGraphReader.processResult(GremlinResultsGraphReader.java:55) ~[spring-data-gremlin-2.1.7.jar:2.1.7]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
```

offending code in MS library is here in GremlinResultsGraphReadrer

```
    private GremlinSource processResult(Result result) {
        final GremlinSource source;
        final Object obj = result.getObject();

        Assert.isInstanceOf(Map.class, obj, "should be an instance of Map");
        @SuppressWarnings("unchecked") final Map<String, Object> map = (Map<String, Object>) result.getObject();

        Assert.isTrue(map.containsKey(PROPERTY_TYPE), "should contain a type property");
        final String type = (String) map.get(PROPERTY_TYPE);

        switch (type) {
            case RESULT_TYPE_VERTEX:
                source = new GremlinSourceVertex();
                vertexResultReader.read(singletonList(result), source);
                break;
            case RESULT_TYPE_EDGE:
                source = new GremlinSourceEdge();
                edgeResultReader.read(singletonList(result), source);
                break;
            default:
                throw new GremlinUnexpectedEntityTypeException("Unexpected result type: " + type);
        }

        return source;
    }...
```

using gremlin core/driver v3.2.4 (default on this build .config) - the server returns a map ok - but the key is '@type'  - and the microsoft constant from static import 'com.microsoft.spring.data.gremlin.common.Constants' is enum with value 'type' so the second assert fails 

if i change the build.config to upgrade to latest gremlin core/driver v 3.4.3 - the the debugger shows the return type as DetachedVertex and not a map - so the first assert fails 

this is all tantilising close to working but the checks /asserts in the result parser fail for gremlin-server 

## Snapshot Code for Reproduce 
```groovy
@SpringBootApplication
class GremlinApplication implements CommandLineRunner {

    @Autowired
    PersonRepository personRepo

    @Autowired
    private RelationRepository relationRepo

    @Autowired
    private NetworkRepository networkRepo

    @Autowired
    private GremlinFactory factory

    private final Network network = new Network(id:"1")

    static void main(String[] args) {
        SpringApplication.run(GremlinApplication, args)
    }

    void run (String... var1) throws Exception {
        //personRepo.deleteAll()

        assert networkRepo
        networkRepo.deleteAll()


        println "prop_type is " + com.microsoft.spring.data.gremlin.common.Constants.PROPERTY_TYPE
        println "created will and maz "
        Person p1 = new Person (id:"2", age:"57", name:"William" )
        Person p2 = new Person (id:"3", age:"56", name:"Maz" )

        Relation r = new Relation (id: "4", name:"married", personFrom:p1, personTo:p2)
        //Person sp = personRepo.save(p)

        println "add people to network vertexes array, add relationship "
        network.vertexes << p1
        network.vertexes << p2
        network.edges << r

        println "save network"
        networkRepo.save(network)

        println "exit()"
    }
...
```

## Branch
* placeholder

## Your Environment
* Version used:
jvm 1.8, spring.framework 5.1.9, spring-data-gremlin v2.1.7, dockerised gremlin-server 3.4.3
* laptop windows 10

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
