### ISSUE TITLE
Cannot deserialize response with any Serializer except `GRAPHSON`

### ISSUE THREAD

**Issue by ghost** [microsoft/spring-data-gremlin#240]
## Expected Behavior
When running the `web-service` example, I expect to be able to use any of the enum values specified in `org.apache.tinkerpop.gremlin.driver.ser.Serializers` as a value for the `serializer` parameter of the `GremlinConfig`.

The fact that this parameter is configurable and not, for example, hard-coded in `GremlinFactory` leads me to believe that it should be possible to use any of the serializers supported by gremlin-driver 3.2.x. However, if we look at `GremlinResultVertexReader` and `AbstractGremlinResultReader` this doesn't seem to be the case.

## Current Behavior
Using the "steps to reproduce" below:

* `GRAPHSON / GraphSONMessageSerializerV1d0 / application/json`
    * Works as expected
* `GRAPHSON_V1D0 / GraphSONMessageSerializerGremlinV1d0 / application/vnd.gremlin-v1.0+json`
    * ```
        java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.LinkedHashMap
        at com.microsoft.spring.data.gremlin.conversion.result.AbstractGremlinResultReader.readProperty(AbstractGremlinResultReader.java:38) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.conversion.result.AbstractGremlinResultReader.lambda$readResultProperties$0(AbstractGremlinResultReader.java:43) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at java.util.HashMap.forEach(HashMap.java:1288) ~[na:1.8.0_111]
        at com.microsoft.spring.data.gremlin.conversion.result.AbstractGremlinResultReader.readResultProperties(AbstractGremlinResultReader.java:43) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultVertexReader.read(GremlinResultVertexReader.java:57) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.conversion.source.AbstractGremlinSource.doGremlinResultRead(AbstractGremlinSource.java:144) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.recoverDomain(GremlinTemplate.java:341) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.findByIdInternal(GremlinTemplate.java:231) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.findById(GremlinTemplate.java:242) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.existsById(GremlinTemplate.java:370) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.notExistsById(GremlinTemplate.java:365) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.save(GremlinTemplate.java:274) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.repository.support.SimpleGremlinRepository.save(SimpleGremlinRepository.java:45) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]

        [...]
        ```
* `GRAPHSON_V2D0 / GraphSONMessageSerializerGremlinV2d0 / application/vnd.gremlin-v2.0+json`
    * ```
        java.lang.IllegalArgumentException: should be one instance of Map: org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertex
        at org.springframework.util.Assert.instanceCheckFailed(Assert.java:655) ~[spring-core-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.util.Assert.isInstanceOf(Assert.java:555) ~[spring-core-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultVertexReader.validate(GremlinResultVertexReader.java:32) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultVertexReader.read(GremlinResultVertexReader.java:52) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.conversion.source.AbstractGremlinSource.doGremlinResultRead(AbstractGremlinSource.java:144) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.recoverDomain(GremlinTemplate.java:341) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.findByIdInternal(GremlinTemplate.java:231) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.findById(GremlinTemplate.java:242) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.existsById(GremlinTemplate.java:370) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.notExistsById(GremlinTemplate.java:365) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.save(GremlinTemplate.java:274) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.repository.support.SimpleGremlinRepository.save(SimpleGremlinRepository.java:45) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]

        [...]
        ```
* `GRYO_V1D0 / GryoMessageSerializerV1d0 / application/vnd.gremlin-v1.0+gryo`
    * ```
        java.lang.IllegalArgumentException: should be one instance of Map: org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertex
        at org.springframework.util.Assert.instanceCheckFailed(Assert.java:655) ~[spring-core-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.util.Assert.isInstanceOf(Assert.java:555) ~[spring-core-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultVertexReader.validate(GremlinResultVertexReader.java:32) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.conversion.result.GremlinResultVertexReader.read(GremlinResultVertexReader.java:52) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.conversion.source.AbstractGremlinSource.doGremlinResultRead(AbstractGremlinSource.java:144) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.recoverDomain(GremlinTemplate.java:341) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.findByIdInternal(GremlinTemplate.java:231) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.findById(GremlinTemplate.java:242) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.existsById(GremlinTemplate.java:370) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.notExistsById(GremlinTemplate.java:365) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.query.GremlinTemplate.save(GremlinTemplate.java:274) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]
        at com.microsoft.spring.data.gremlin.repository.support.SimpleGremlinRepository.save(SimpleGremlinRepository.java:45) ~[spring-data-gremlin-2.1.7.jar!/:2.1.7]

        [...]
        ```

I didn't bother testing `GRYO_LITE_V1D0` as this is not supported by [the platform I want to use in production](https://docs.aws.amazon.com/en_pv/neptune/latest/userguide/access-graph-gremlin-differences.html).


## Possible Solution
Unknown.

Is it the intention of this project to support multiple serialization methods?

## Steps to Reproduce (for bugs)
1. Setup Gremlin server:
    1. Download and install [Gremlin Server 3.3.8](https://www.apache.org/dyn/closer.lua/tinkerpop/3.3.8/apache-tinkerpop-gremlin-server-3.3.8-bin.zip)
    1. Run Gremlin Server with the config provided below.
1. For each value in `org.apache.tinkerpop.gremlin.driver.ser.Serializers`:
    1. Setup Spring Data Gremlin:
        1. Edit `examples/web-service/src/main/resources/application.yml` to use `endpoint: localhost` and `port: 8889`.
        1. Change `serializer` to the serializer under test.
        1. Build `web-service` example (I used `mvn clean package`)
    1. Run Gremlin Server: `bin/gremlin-server.sh conf/gremlin-server-ci.yaml`
    1. Run the example:
        ```
        $ cd examples/web-service/target
        $ java -jar spring-data-gremlin-web-service-0.0.1.BUILD-SNAPSHOT.jar
    1. Attempt to save something: `curl -X PUT -H "Content-Type: application/json" -d '{"id": "1234"}' http://localhost:8080/services/`

## Snapshot Code for Reproduce 
https://github.com/microsoft/spring-data-gremlin/tree/master/examples/web-service

Gremlin server config:
```
host: localhost
port: 8889
gremlinPool: 8
threadPoolWorker: 8
scriptEvaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphs: { graph: conf/gremlin-server-ci.properties }

scriptEngines: {
  gremlin-groovy: {
    plugins: { org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
               org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]}}}}

serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { ioRegistries: [org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV1d0] } }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0, config: { ioRegistries: [org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV2d0] } }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { ioRegistries: [org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV1d0] } }
ssl: { enabled: false }
```

gremlin-server-ci.properties:
```
gremlin.graph=org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph
gremlin.tinkergraph.vertexIdManager=ANY

```

## Branch
* master

## Your Environment
* Version used: `6f9a925100c4b12fc79b9e4e2248c4f4c0e78abb`
* Operating System and version (desktop or mobile): MacOS 10.14.6
* SDK version:

**Comment by saragluna** [comment]
Thanks for reporting this. GRAPHSON is indeed the only serializer we currently support. We will consider this and if this feature is important for you, welcome to contribute.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
